# This workflow will take a list of users and at each invocation it will change assignee to the next one on the list
name: Rolling issue assignment
on:
  workflow_call:
    inputs:
      users:
        required: true
        type: string
      issue:
        required: true
        type: number

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const baseReq = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ inputs.issue }}
            };
            const issue = await github.rest.issues.get(baseReq);
            const candidates ="${{ inputs.users }}".split(",");
            let newAssignee = "";
            console.log(issue);
            if (!issue || issue.assignees.length === 0) {
              newAssignee = candidates[0];
            } else {
              const curAssignee = issue.assignees[0].login;
              await github.rest.issues.removeAssignees({...baseReq, assignees: [curAssignee]});
              for (let i = 0; i < candidates.length; i++) {
                if (candidates[i] === curAssignee) {
                  newAssignee = candidates[(i + 1) % candidates.length];
                  break
                }
              }
            }
            await github.rest.issues.addAssignees({...baseReq, assignees: [newAssignee]});
