on:
  issues:
    types:
      - reopened
      - opened
      - labeled
  workflow_dispatch:
  schedule:
    - cron: 30 * * * *

jobs:
  assign:
    uses: lahabana/github-pm-groomer/.github/workflows/rolling-issue-assignment.yml@master
    with:
      issue: 4
      users: lahabana,guillaumemolter
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $DATA
        env:
          DATA: ${{ toJSON(github.event) }}
