on:
  issues:
    types:
      - reopened
      - opened
      - labeled
  workflow_dispatch:
  schedule:
    - cron: 20 * * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $DATA
        env:
          DATA: ${{ toJSON(github.event) }}
