on:
  issues:
    types:
      - reopened
      - opened
      - labeled
  workflow_dispatch:
  schedule:
    - cron: 10 * * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event }}
