on:
  issues:
    types:
      - reopened
      - opened
      - labeled
  workflow_dispatch:
  schedule:
    - cron: 30 * * * *

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/rolling-issue-assignment.yaml@master
        with:
          issue: 4
          users: lahabana,guillaumemolter
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $DATA
        env:
          DATA: ${{ toJSON(github.event) }}
